### ISSUE TITLE
Cannot read property 'be' of undefined

### ISSUE THREAD

**Issue by marcofranssen** [chaijs/chai-as-promised#41]
I'm trying to use chai-as-promised. However I always get errors on the be property because should is undefined. I'm using q as promise library. 

Part of testcase:

``` JavaScript
'use strict';

var sinon = require('sinon'),
    sinonChai = require('sinon-chai'),
    chaiAsPromised = require("chai-as-promised"),
    chai = require('chai'),
    should = chai.should(),
    expect = chai.expect,
    config = require('./../lib/modules/configuration'),
    Configuration = config.Configuration;

chai.Assertion.includeStack = true;
chai.use(chaiAsPromised);
chai.use(sinonChai);

beforeEach(function() {
    module.sinon = sinon.sandbox.create();
});

afterEach(function(){
    module.sinon.restore();
});

describe('loading a non existing configuration', function () {
    var configPromise;

    before(function () {
        var configuration = new Configuration('failing/path/');
        configPromise = configuration.load();
    });

    it('should result in an error', function () {
        //this succeeds
        configPromise.then(null, function (err) {
            expect(err).to.exist;
        });
        //this fails with the error 
        configPromise.should.be.rejected.and.notify(done);
    });

    after(function () {
        config.reset();
    });
});
```

The error:

```
TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (/myproj/spec/configuration.spec.js:25:29)
      at Test.Runnable.run (/myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (/myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:358:10)
      at /myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:404:12
      at next (/myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:284:14)
      at /myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:293:7
      at next (/myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:237:23)
      at Object._onImmediate (/myproj/node_modules/grunt-mocha-chai-sinon/node_modules/mocha/lib/runner.js:261:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by reggi** [comment]
This fixed it for me.

```js
import chai from 'chai'
import chaiAsPromised from 'chai-as-promised'

chai.should()
chai.use(chaiAsPromised)
```

**Comment by ttonteri** [comment]
More than eight years have passed, but I can nevertheless confirm that @reggi's post from 10.4.2016 was still the much needed tip to get this working... For whatever reason, calling `chai.should()` before the `use()` enables the proper functionality of the should-chains. I just wish this would be more clear/explicit in the docs.
